language: node_js

node_js:
- "9"

cache:
  directories:
  - ~/.npm
  - ~/.cache

install:
- yarn add

script:
- yarn build

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: yandex-airport
