language: node_js

node_js:
- "9"

cache:
  directories:
  - ~/.npm
  - ~/.cache

install:
- npm install

script:
- npm build

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: yandex-airport
